DISTRIBUTED_CONFIG_FIELD = "__kedro_azure_ml_distributed_config__"
PARAMS_PREFIX = "params:"

# MLflow integration env vars (set by generator, read by MlflowAzureMLHook)
KEDRO_AZURE_ML_MLFLOW_ENABLED = "KEDRO_AZURE_ML_MLFLOW_ENABLED"
KEDRO_AZURE_ML_MLFLOW_RUN_NAME = "KEDRO_AZURE_ML_MLFLOW_RUN_NAME"
KEDRO_AZURE_ML_MLFLOW_EXPERIMENT_NAME = "KEDRO_AZURE_ML_MLFLOW_EXPERIMENT_NAME"
KEDRO_AZURE_ML_MLFLOW_NODE_NAME = "KEDRO_AZURE_ML_MLFLOW_NODE_NAME"
